### ISSUE TITLE
TypeError: Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by cambiph** [JaySunSyn/cypress-daywalker#3]
Hey there,

Nice work on the plugin!
I have a question about handling the Spring Security login screen.
In my before function, I have to log in to the application but your plugin throws an exception:

This is the code I use:

```javascript
before(function() {
    cy.visit('http://localhost:8080');
    cy.get('[name=username]').type('user');
    cy.get('[name=submit]').click();
})
```

Cypress throws:

> TypeError: Cannot read property 'store' of undefined

Do I need to disable your plugin on the login page?

Thanks in advance.
Regards

**Comment by JaySunSyn** [comment]
Hi there, please make sure that you use the latest version of the plugin. Let me know if you have still issues.

**Comment by cambiph** [comment]
I am using version 0.0.5.
The before-function is implemented under `cypress/support/index.js`.
Could that be the problem?

**Comment by eiswind** [comment]
I see the same error with 0.0.5, seems to have nothing to do with the spring login page as I'm running a vaadin app.

**Comment by JaySunSyn** [comment]
I overwrite the visit command to inject the daywalker script. 

- Do you see a 404 in the console?
- Do you include the cypress-daywalker/commands in your commands.js file?

---

Another option is to try this (let me know if it worked out):

**Include the daywalker script manually:**

either via a) At the top of your entrypoint e.g. **`index.html`** add following script tag
```html
    <script src="./node_modules/cypress-daywalker/cypress-daywalker.js"></script>
```
or via b) Dynamically add the daywalker script before each test

```javascript
context('Default', () => {
  before(() => {
    cy.on('window:before:load', (w) => {
      const script = w.document.createElement('script');
      script.src = '/node_modules/cypress-daywalker/cypress-daywalker.js';
      w.document.querySelector('head').appendChild(script);
    });
    cy.visit('http://localhost:3000/');
  });
  it('input gets filled', () => {
    ...
  });
});
```

**Comment by cambiph** [comment]
When running the tests, I see the following:

```shell
GET /__/ 200 19.288 ms - -
GET /__cypress/runner/cypress_runner.css 200 33.806 ms - -
GET /__cypress/runner/cypress_runner.js 200 282.585 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.6.3 200 2.058 ms - 71896
GET /__cypress/iframes/integration/sample_spec.js 200 17.706 ms - 725
GET /__cypress/tests?p=cypress/integration/sample_spec.js-467 200 1403.883 ms - 694
GET /__cypress/tests?p=cypress/support/index.js-210 200 1440.585 ms - -
GET /login 200 4.993 ms - -
GET /node_modules/cypress-daywalker/cypress-daywalker.js 404 55.070 ms - -
```

This means that using `import 'cypress-daywalker/commands'`in `command.js`does not seem to work.

Secondly, trying your proposed fix like this:

```javascript
context("App", () => {
  beforeEach(() => {
    cy.on("window:before:load", w => {
      const script = w.document.createElement("script");
      script.src = "/node_modules/cypress-daywalker/cypress-daywalker.js";
      w.document.querySelector("head").appendChild(script);
    });
  });

  it("app opens", function() {
    cy.get("test-app").should("be.visible");
    cy.get("#templatebutton").should("be.visible");
  });
});
```
returns:
```
 0 passing (7s)
  1 failing

  1) App app opens:
     CypressError: Timed out retrying: Expected to find element: '#templatebutton', but never found it.
      at Object.cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:63065:11)
      at Object.throwErr (http://localhost:8080/__cypress/runner/cypress_runner.js:63030:18)
      at Object.throwErrByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:63057:17)
      at retry (http://localhost:8080/__cypress/runner/cypress_runner.js:56635:16)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:48746:18
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:124314:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:122332:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:122389:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:122434:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:122509:18)
      at Async._drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:119238:16)
      at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:119248:10)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:119122:14)
      at <anonymous>
```

Not sure what to do next.
If you need more info, please let me know.

**Comment by JaySunSyn** [comment]
Can I see your html file?

**Comment by cambiph** [comment]
> Can I see your html file?

Any idea on how I can copy the rendered HTML with the shadow DOM?
Been trying to copy it, but the shadowDOM does not ge copied.
I can provide you with a screenshot of the code, but I do not think that works well, or does it?
https://imgur.com/gWE6VAf

**Comment by JaySunSyn** [comment]
I don't see a custom element with the id `templatebutton` in your screenshot, or do I miss it? Please join the gitter chat https://gitter.im/cypress-daywalker/

**Comment by cambiph** [comment]
> I don't see a custom element with the id `templatebutton` in your screenshot, or do I miss it? Please join the gitter chat https://gitter.im/cypress-daywalker/

Updated the screenshot

**Comment by johndalvik** [comment]
Have the same issue, any update ?

**Comment by cambiph** [comment]
@johndalvik I provided Jay with a sample app so he can debug. We will just have to wait for feedback.

**Comment by JaySunSyn** [comment]
@johndalvik which stack do you use?

Did you add the script to your entry point or do you dynamically inject it? Did you try to use a cdn instead? See here: https://github.com/JaySunSyn/cypress-daywalker/blob/master/README.md#via-a-dynamic-script-tag

**Comment by johndalvik** [comment]
@JaySunSyn 
Actually I just extended your example a little bit, for checking if cypress is gonna work for my project.
But I'm getting the error stated above.

**Comment by JaySunSyn** [comment]
This error just means that `cypress-daywalker.js` did not get injected. Either your path is wrong or your app cannot serve node_modules files properly or you forgot to do this at all https://github.com/JaySunSyn/cypress-daywalker#3-add-the-daywalker-script

If you share the code, I can look into it

**Comment by JaySunSyn** [comment]
@cambiph can you try this please:

```
beforeEach(() => {
    cy.on('window:before:load', (w) => {
      const script = w.document.createElement('script');
      script.src = 'https://cdn.jsdelivr.net/gh/jaysunsyn/cypress-daywalker@0.1.1/cypress-daywalker.js';
      w.document.querySelector('head').appendChild(script);
    });

    cy.visit('http://localhost:8080/login');
  });

  it('login', () => {
    cy.get('input[name=username]').setProp('gebruiker');
    cy.get('input[name=submit]').click();
  });
```

**Comment by cambiph** [comment]
Hey, 

Sorry for the late reply.
I no longer have the error stating that 'store' is undefined but I have the following.
Using following code:

```javascript
describe('App', () => {

  beforeEach(() => {
    cy.on('window:before:load', (w) => {
      const script = w.document.createElement('script');
      script.src = 'https://cdn.jsdelivr.net/gh/jaysunsyn/cypress-daywalker@0.1.1/cypress-daywalker.js';
      w.document.querySelector('head').appendChild(script);
    });
  });

  it('Referentiedata download bevat juiste href', () => {
      cy.get('#downloadreferentiedatalink').should('have.attr', 'href', 'rest/referentiedata');
  });
```

Cypress throws:
```shell
Command:   assert
cypress_runner.js:160755 Subject:   jQuery.fn.init(0)context: documentlength: 0prevObject: jQuery.fn.init(1)selector: "#downloadreferentiedatalink"__proto__: Object(0)
cypress_runner.js:160755 Message:   expected { Object (length, prevObject, ...) } to have attribute href
cypress_runner.js:160755 Error:     Uncaught Error: [object Event]

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
    at createErrFromMsg (http://localhost:8080/__cypress/runner/cypress_runner.js:56209:14)
    at Object.createUncaughtException (http://localhost:8080/__cypress/runner/cypress_runner.js:56216:13)
    at Object.onUncaughtException (http://localhost:8080/__cypress/runner/cypress_runner.js:59100:20)
    at onError (http://localhost:8080/__cypress/runner/cypress_runner.js:58599:39)
From previous event:
    at run (http://localhost:8080/__cypress/runner/cypress_runner.js:58784:15)
    at Object.cy.(anonymous function) [as get] (http://localhost:8080/__cypress/runner/cypress_runner.js:59012:11)
    at Context.runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:59142:20)
    at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:27558:21)
    at Test.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:27551:7)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:62062:28
    at <anonymous>
From previous event:
    at Object.onRunnableRun (http://localhost:8080/__cypress/runner/cypress_runner.js:62057:20)
    at $Cypress.action (http://localhost:8080/__cypress/runner/cypress_runner.js:57439:51)
    at Test.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:61123:20)
    at Runner.runTest (http://localhost:8080/__cypress/runner/cypress_runner.js:28021:10)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:28127:12
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:27941:14)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:27951:7
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:27883:14)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:27914:7
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:62027:16)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:62039:11
From previous event:
    at onNext (http://localhost:8080/__cypress/runner/cypress_runner.js:62038:57)
    at done (http://localhost:8080/__cypress/runner/cypress_runner.js:27519:5)
    at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:27576:7)
    at Hook.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:27551:7)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:62062:28
From previous event:
    at Object.onRunnableRun (http://localhost:8080/__cypress/runner/cypress_runner.js:62057:20)
    at $Cypress.action (http://localhost:8080/__cypress/runner/cypress_runner.js:57439:51)
    at Hook.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:61123:20)
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:27897:10)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:27919:5
    at timeslice (http://localhost:8080/__cypress/runner/cypress_runner.js:23160:27)
cypress_runner.js:160755 Snapshot:  The snapshot is missing. Displaying current state of the DOM.
```
However, element `#downloadreferentiedatalink` is present under the shadowDom so I believe the object is found but its attributes cannot be found.
![image](https://user-images.githubusercontent.com/1628243/58158087-01d37380-7c7a-11e9-9df6-45d961c89b25.png)

**Comment by JaySunSyn** [comment]
Please confirm if this is still the case with version `0.2.1`

**Comment by JaySunSyn** [comment]
Closing for now, tests succeed consistently as per https://travis-ci.com/JaySunSyn/cypress-daywalker/builds/

Feel free to re-open.
